### ISSUE TITLE
Make it possible to easily customize the landing page

### ISSUE THREAD

**Issue by rachoac** [mi-squared/volunteer-portal#205]
"
Thank you, volunteering to assist Pathway To Health and the citizens of the Greater Los Angeles area.

INSTRUCTIONS:

1. Please fill out all areas of the form that pertains to you. It is VERY IMPORTANT that you double check that you did not miss any question before moving on the next section.
2. RETURNING VOLUNTEERS: Click the Returning Volunteer link and the Forgot Password link.  Enter your email address, you will receive an email with a link to change your password. Click that link and enter a password. Next please go through the entire form and update your information and PLEASE answer all questions VERY IMPORTANT. 

Blessings,
Thank You"

**Comment by tmccormi** [comment]
This wording needs to be on the main login page Stat :-)

**Comment by rachoac** [comment]
Yep we are looking at it

**Comment by rachoac** [comment]
Done deployed to production site
