### ISSUE TITLE
ESign - Click thru Terms text needed

### ISSUE THREAD

**Issue by tmccormi** [mi-squared/volunteer-portal#26]
This is the current text at at the bottom of the existing form:

By submitting this form, you're granting:
Pathway to health, 1234 happy street, Silver Spring, MD 55555, United States
http://www.pathwaytohealthvolunteer.org/
permission to email you. You can revoke permission to mail to your email address at any time using the SafeUnsubscribeTM, found at the bottom of every email.

**Comment by tmccormi** [comment]
Rupert will send test for this page

**Comment by rachoac** [comment]
Updated the text

**Comment by tmccormi** [comment]
Customer provided a PDF for them to view and then agree to.   Please add a link to the PDF on the agreement page

Document is in the GDrive folder

**Comment by rachoac** [comment]
@tmccormi is the PDF something they need to sign and upload?

**Comment by rachoac** [comment]
Also ... what text should we include in the esign click thru, when referencing this PDF?

**Comment by tmccormi** [comment]
No they just need to read it and agree to the terms.  Words to that effect

Tony McCormick
www.mi-squared.com
On Nov 17, 2015 7:59 PM, "rachoac" <notifications@github.com> wrote:

> Also ... what text should we include in the esign click thru, when
> referencing this PDF?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mi-squared/volunteer-portal/issues/26#issuecomment-157598761>
> .
>

-- 
Please be aware that e-mail communication can be intercepted in 
transmission or misdirected. Please consider communicating any sensitive 
information by telephone.  The information contained in this message may be 
privileged and confidential. If you are NOT the intended recipient, please 
notify the sender immediately with a copy to hipaa-security@mrsb-ltd.com and 
destroy this message.

**Comment by rachoac** [comment]
done. the pdf is linked on the esign page and is downloadable from there.
