### ISSUE TITLE
Will use AWS S3 bucket for document storage 

### ISSUE THREAD

**Issue by tmccormi** [mi-squared/volunteer-portal#28]
Rupert will create an account and send credentials.

Format for storage should be similar to OpenEMR:  A directory structure as follows:
/-root
---> Volunteers
------->VOLUNTEER_ID
------------> FILLED FORM 1
------------> FILLED FORM 2
------------> FILLED FORM ...
---> BlankForms
------> Medical
------> Legal
------> Nursing
------> Dental
------> Chaplaincy
------> ... etc

Blanks forms links would be displayed on a page accessible after volunteer has agreed to terms and logged back in.  Filter forms available by Volunteer Areas selection

Forms the volunteer has uploaded would be listed on separate section of that page and allow them to delete the form if desired and upload new forms

**Comment by tmccormi** [comment]
https://931667677821.signin.aws.amazon.com/console
developers
Y7QkSM[ulOA|

**Comment by tmccormi** [comment]
I tried this and it requires that we change the password at login, but ... when I try I get:
User is not authorized to perform iam:ChangePassword.

**Comment by tmccormi** [comment]
New URL for console access
https://931667677821.signin.aws.amazon.com/console

Tony has password

**Comment by rachoac** [comment]
@tmccormi is there some guidance on where this document upload page fits into the current page flow?
also, any guidance on what we want to see there in terms of layout and verbiage

**Comment by tmccormi** [comment]
Yes, It should be the first page you see when you log back into you account.  With a link to continue to the review/edit data fields after that.

**Comment by rachoac** [comment]
Feature complete, working on bugs now
