### ISSUE TITLE
What areas would you like to volunteer in?

### ISSUE THREAD

**Issue by tmccormi** [mi-squared/volunteer-portal#29]
List needs to be updated / enhance per below and verbiage added to make it clear that you can select multiple areas.

Note: ignore the color thing (that's tee-shirt color for the area)

•       Academy Bus Transportation-Black
•       Active Manual Relaxation/Hydrotherapy-Royal Blue
•       Audio Visual-Black
•       Audio Visual Food Demonstration-Black
•       Audiology-Heather grey
•       Beautician/Barber Services-Neon Green-bib-Shirt Color is Black
•       Central Supply-White
•       Chaplaincy-Brown
•       Children’s Department Adult Volunteer-Black
•       Communications-Media-Black
•       Director’s/Assistant Director’s-Black
•       Exit Management-Black
•       Eye Care-Purple
•       Food Demonstration-Black
•       Food Services-Black
•       Hospitality-Black-with Varied Leis
•       Hospitality Decorations-Black
•       Hospitality-Tour Guide-Black
•       Interpretation-Black Shirt-White Leis/White Arm Bands
•       Lab-White
•       Lifestyle-Charcoal
•       Mental Health-Hunter Green
•       Music Therapy-Black
•       Pediatrics-Sky Blue
•       Pharmacy-White
•       Plant Services-Black
•       Podiatry-Navy Blue
•       Primary Care-White
•       Program Committee-Black
•       PT/OT-Heather Grey
•       Radiology-White
•       Registration-Black
•       Respiratory Therapy-White
•       Registration-Black
•       Security-Black
•       Surgery-Red
•       Triage-White
•       Volunteer Registration-Black
•       Women’s Health-Burgundy

**Comment by rachoac** [comment]
Updated
