### ISSUE TITLE
Import of current list of volunteers into database

### ISSUE THREAD

**Issue by tmccormi** [mi-squared/volunteer-portal#32]
Post alpha test.   Need to import the document: Final EXCEL
https://docs.google.com/spreadsheets/d/1B7ItS5HStKwwPmbBo5mdQANJnZfPyl0HDYhWGXIB_ag/edit?usp=sharing

This is a multi-TAB file by area of volunteer.

**Comment by tmccormi** [comment]
Updated import data in better formats have been added to the google share - Aron will have access the data.  These are for previous events San Antonio and Spokane and are in CSV format dumped from the database instead of XLS tabbed data.   Should be significantly easier to map.

Need to know ASAP if there are any manual actions that PTH needs to do to this data to make it possible to import it in the new database.

There will be one more data set, the current list of volunteers for the April LA event target.

**Comment by rachoac** [comment]
@tmccormi should we work on this?

**Comment by tmccormi** [comment]
Yes

Tony McCormick
www.mi-squared.com
On Dec 21, 2015 11:35 PM, "rachoac" <notifications@github.com> wrote:

> @tmccormi <https://github.com/tmccormi> should we work on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mi-squared/volunteer-portal/issues/32#issuecomment-166503112>
> .
>

-- 
Please be aware that e-mail communication can be intercepted in 
transmission or misdirected. Please consider communicating any sensitive 
information by telephone.  The information contained in this message may be 
privileged and confidential. If you are NOT the intended recipient, please 
notify the sender immediately with a copy to hipaa-security@mrsb-ltd.com and 
destroy this message.

**Comment by rachoac** [comment]
The san antonio and spokane lists have been imported into production (https://www.ybpth.net/)
