### ISSUE TITLE
Under "Have You volunteered for best pathway to health

### ISSUE THREAD

**Issue by pathwaytohealth** [mi-squared/volunteer-portal#36]
1. Capatalize Your Best Pathway To Health
2. Insert the same multiple choice DDM from "What areas would you like to volunteer in"

**Comment by pathwaytohealth** [comment]
7) On Volunteering Detail page. 

A) Please change "Have you volunteered for your best pathway to health before" to:
 Have you volunteered for Your Best Pathway to Health before? 
B) If you click "Yes" the next question is What area did you work in?  
C) Please change to: In what areas have you volunteered? 
D) Please add to the What area did you work in box the same drop down list from the drop down box "What area would you like to volunteer in?" (Same list and same format) - Please allow for multiple selections in this box. 
E) Please change "In what capacity did you work" to: What was your position.
F) Please move Are you part of a volunteer group and it's drop down box asking what is your volunteer group to the area after "are you a student volunteer" on the prior page.

**Comment by rachoac** [comment]
done
