### ISSUE TITLE
License # 

### ISSUE THREAD

**Issue by pathwaytohealth** [mi-squared/volunteer-portal#38]
License field needed in each section where license information is requested

**Comment by rachoac** [comment]
@pathwaytohealth isn't this already handled in https://github.com/mi-squared/volunteer-portal/issues/47?

**Comment by tmccormi** [comment]
looks like it to me.   Rupert can you include a screen shot of what you are referring to?

**Comment by rachoac** [comment]
@pathwaytohealth @tmccormi is there something not already handled by #47 that needs to be done here? Otherwise I will close this issue.

**Comment by tmccormi** [comment]
Rearranged the fields to work more logically
