### ISSUE TITLE
Dental and dental sub-specialties

### ISSUE THREAD

**Issue by pathwaytohealth** [mi-squared/volunteer-portal#39]
Dental and dental sub-specialties we need to add Dental and dental sub-specialties fields under medical professionals

**Comment by rachoac** [comment]
@pathwaytohealth are you asking for 2 new fields, or just one more field called "Dental and dental sub-specialties"?

**Comment by tmccormi** [comment]
There is supposed to be a "sub specialty free text box" for all.   I would just add that under the specialty selection list

**Comment by rachoac** [comment]
@tmccormi so are you saying we can add a new free text entry field "Medical or dental subspecialties", and that will satisfying this ticket?

**Comment by rachoac** [comment]
Renamed existing "List any medical sub-specialties" field to ""List any sub-specialties"
