### ISSUE TITLE
Date Fields should enforce masking

### ISSUE THREAD

**Issue by tmccormi** [mi-squared/volunteer-portal#4]
Don't default dates (just show format)
display needs to be MM/DD/YYYY and/or MM-DD-YYYY per customer
Select widget not useful for dates that are far away

**Comment by rachoac** [comment]
format is now shown as placeholder.

**Comment by rachoac** [comment]
Select widget has been removed, we'll go with enforced masking

**Comment by rachoac** [comment]
Added date field masking (mm/dd/yyyy)
