### ISSUE TITLE
Error Screen

### ISSUE THREAD

**Issue by pathwaytohealth** [mi-squared/volunteer-portal#41]
4) The notice that there are fields in error - is at top of screen not seen while at bottom and the page is not moving forward.  Areas of problem to progress are not highlighted so applicant knows what needs to be fixed so they can continue to next page.  

A) Please move error message to bottom of screen - near continue button so easily visible. 
B)  Please highlight area that is causing error message to be given.

**Comment by rachoac** [comment]
done
