### ISSUE TITLE
 "Are you volunteering as a medical professional."

### ISSUE THREAD

**Issue by pathwaytohealth** [mi-squared/volunteer-portal#45]
On the drop down if answering yes to "Are you volunteering as a medical professional."

A) Please alphabetize list of specialities currently there and please add: 
Anesthesiology
Dentistry
Emergency
Physical Therapy / Occupational Therapy
Orthopedics
Ear Nose & Throat
Oral Surgery
Gerontology
Psychiatry
Public Health
Oncology
Orthodontia
B) To match entry style: 
Please change GI to Gastroenterology
Please change GYN Onc to Gynecology Oncology 
C) Please allow multiple sections in this drop down field.

**Comment by rachoac** [comment]
done
