### ISSUE TITLE
Discipline licensed in.

### ISSUE THREAD

**Issue by pathwaytohealth** [mi-squared/volunteer-portal#47]
Discipline licensed in.

A) Please change wording to: 
Professional license or certification in:
B) Please alphabetize and add in drop down box - same format as previous drop down boxes.
Doctor
Dentist
Dental Hygienist
Dental Assistant
Physical Therapist
Occupational Therapist
Social Worker
Respiratory Therapist
Laboratory Technician
Certified Radiologic Technologist 
Ultrasound Technician
Physician's Assistant
Advanced Registered Nurse Practitioner
Certified Registered Nurse Anesthetist
Certified Nurse Midwife
Certified Midwife
Certified Nursing Assistant
Registered Nurse
Licensed Vocational or Practical Nurse
Paramedic
Emergency Medical Technician
Audiologist
Certified Massage Therapist
Naturopath
Osteopath
Registered Dietitian
Optician
Optometrist
Ophthalmologist
Chiropractor
Speech & Language Pathologist
Surgical Technician
Certified Counselor
Podiatrist
Licensed Massage Therapist
Drivers License Commercial Class A
Drivers License Commercial Class B
Drivers License Commercial Class C
Other: 
C) Please Add:  Fill in box for License Number
D) Under State of License
- Please format scroll the same as the other boxes scroll functions.

**Comment by rachoac** [comment]
@pathwaytohealth i am unclear what you mean here?

C) Please Add: Fill in box for License Number
D) Under State of License

? are you wanting some kind of extra static text reminder for them to fill in the license number field (which already exists)?

**Comment by rachoac** [comment]
ah no, i was wrong license number doesn't exist -- now i get it

**Comment by rachoac** [comment]
done
