### ISSUE TITLE
Aside from any emergencies are you willing to help the entire time?

### ISSUE THREAD

**Issue by pathwaytohealth** [mi-squared/volunteer-portal#50]
A) Please define "the entire time" with dates.
B) Please move these two questions out from under this question set and set up as individual questions after the "aside from any emergencies" question - to obtain better commitment for these activities as they would be included in the entire time. 

Which pre-event activities can you help with?
Logistics-Truck Unloading
Central Supply/ Inventory
Departmental set up/organization
Which post-event activities can you help with?
Logistics tear down
Logistics Truck loading
Part I- Patient Follow up (labs sorting/organizing)
Part II-Patient Follow up (labs sorting/organizing)
Health Information Centers follow up

**Comment by rachoac** [comment]
Are we planning to support admin customizable event dates?

**Comment by tmccormi** [comment]
The idea (originally) was to have a list of upcoming events and allow them to pick which event they are registering for.   For this first time we can just assume the LA event.     Need to get the specific dates from Rupert.

**Comment by pathwaytohealth** [comment]
The Dates for LA is April 26th - April 30th 2016

**Comment by rachoac** [comment]
done
