### ISSUE TITLE
Remove Race / Ethnicity

### ISSUE THREAD

**Issue by rachoac** [mi-squared/volunteer-portal#69]
Please remove this entire drop down please.  This is non-essential information. I believe this was discussed in the conference call a few weeks ago.

**Comment by azeazas** [comment]
done

**Comment by rachoac** [comment]
@azeazas we probably need to add a downgrade script to the laravel side of things if we haven't done it yet. Lets create a new ticket for removing a field from laravel and we can look at it together tomorrow
