### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by pathwaytohealth** [mi-squared/volunteer-portal#82]
1.I tried to do this today  and after 2 screens, I believe, I got the "error saving" message and could not continue. It would not save the information.

2I’ve just tried to fill out the Application form.  All went well with the first page, but when I hit “Continue” at the bottom I received a long error message that started with “error saving application!” and then an option to click at the bottom if I didn’t want to see any more error messages.  I clicked that option, but then I couldn’t get past the first page.  When I clicked “Continue” at the bottom it would go nowhere and so I got out.  When I reenter the site, it appears that my data was not saved at all.
 
Thanks for all you’re doing to make it happen!  Let me know if I need to try something else!

I am using Window 7 professional and Google chrome or explorer 9 browsers.

3. Rupert I can not log in on registered page and this is the message I get when I try to register.
![img_2922](https://cloud.githubusercontent.com/assets/15783922/11536244/5c8adbf0-98cc-11e5-988c-4470f5ed1972.JPG)

4.Tried to register as a "New Volunteer", accepted initial page with setting password.  Attempted to continue and will not allow to proceed with pastor's email (even though that field does not have a red *) and then once filled got an error box and can not continue any further.

5. This is Lester Haag, department of Podiatry.  I tried to fill out the vol application and when I sent to save it my computer froze up.  I have a Mac……….site opened normal……….filled in the info………pushed save and it would not work.

6. Error message exiting volunteer registration page using Safari
![benny error message](https://cloud.githubusercontent.com/assets/15783922/11536378/13d95502-98cd-11e5-817c-7bd953e0339d.png)

7. I was able to register under new applicant, as I do not have a password even though I have attended all the events so far.  The first two pages worked fine, but it would not let me continue after that.

**Comment by rachoac** [comment]
@azeazas @tryangul I think once we get the submit button greying out while the form is submitting, we can probably have @pathwaytohealth ask one of the testers to try again.

@pathwaytohealth its super critical to get the exact operating system, browser type and browser version that these people were using, so we can troubleshoot and validate that they work in those browsers. Once we're ready for them to try again, please make sure they indicate those things if the bugs still persist... 
Thanks,
Aron

**Comment by rachoac** [comment]
@pathwaytohealth we should try this again
